#!/usr/bin/env bash
# configures a new Ubuntu machine installing Nginx

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" >> /var/www/html/index.html
sudo service nginx start
