#!/usr/bin/env bash
# configures a new Ubuntu machine installing Nginx

sudo apt-get -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP' # permisos para el puerto 80
echo "Holberton School" > index.html
sudo mv index.html /var/www/html/

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

ARG_SED="/listen 80 default_server;/a "
ARG_SED="${ARG_SED}\\\trewrite ^/redirect_me https://www.youtube.com permanent;\n"
ARG_SED="${ARG_SED}\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html "
ARG_SED="${ARG_SED}{\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"

sudo sed -i "${ARG_SED}" /etc/nginx/sites-available/default

H_NAME=$(cat /etc/hostname)
ARG_SED="/location \/ {/a \\\t\tadd_header X-Served-By $H_NAME;"
# these sed adds two times the same line
sudo sed -i "${ARG_SED}" /etc/nginx/sites-available/default
sudo service nginx restart
