#!/usr/bin/env bash
#displays To infinity and beyond indefinitely.

echo $$ >> /var/run/holbertonscript.pid

trap 'echo "I hate the kill command" ;
sudo rm /var/run/holbertonscript.pid ;exit' SIGTERM

trap 'echo "Y U no love me?!" ;
sudo rm /var/run/holbertonscript.pid ;exit' SIGINT

infinity=True
while [ $infinity ]
do
	echo "To infinity and beyond"
	sleep 0.5
done
