#!/usr/bin/env bash
#this displays "Holberton School" 10 times with while loop

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i = 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done
