#!/usr/bin/env bash
# displays all active IPv4 IPs on the machine it’s executed on
#ip -4 -o address | cut -d "/" -f 1 | rev | cut -d " " -f 1 | rev | tac
ifconfig | grep "inet addr:" | cut -d ":" -f 2 | cut -d " " -f 1
